version: '3.12'

services:
  grafana:
    image: grafana/grafana:10.4.0
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    environment:
      # Habilitar MFA
      - GF_SECURITY_ENABLE_MFA=true
      - GF_SECURITY_MFA_TOKEN_VALIDITY=300

      # Usuário admin inicial (opcional)
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin

    volumes:
      # Persistência REAL do Grafana (não versionada)
      - ./data:/var/lib/grafana

      # Configurações do Grafana
      - ./grafana.ini:/etc/grafana/grafana.ini

      # Provisionamento (datasources + dashboards provider)
      - ./grafana/provisioning:/etc/grafana/provisioning

      # Dashboards JSON versionadas pelo GitHub
      - ./grafana/dashboards:/var/lib/grafana/dashboards
